version: '3.9'

services:

  file_service:
    build: .
    container_name: file_service
    command: "uvicorn app.cmd.main:app --reload --host 0.0.0.0 --port 10001"
    ports:
      - "127.0.0.1:10001:10001"

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9008:9008"
      - "9011:9011"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
 minio-storage:
