version: '3.9'

services:

#  file_service:
#    build: .
#    container_name: file_service
#    command: "uvicorn app.cmd.main:app --reload --host 0.0.0.0 --port 10001"
#    ports:
#      - "127.0.0.1:10001:10001"

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  db_postgres:
    image: postgres:16.1
    container_name: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
 minio-storage:
 postgres_data:
